### ISSUE TITLE
Color picker instead of colors list selection

### ISSUE THREAD

**Issue by PoomSmart** [insanj/BlurBar#5]
I think this is a good idea. By allowing users to desire the blur tint color of the status bar. There are some open-source color picker we could use for further development. (such as NKO color picker)

**Comment by insanj** [comment]
Agreed. This shouldn't be tricky at all, either, it'd be the same sort of thing [implemented in Circlet](https://github.com/insanj/Circlet/blob/master/CRPrefs/CRListItemsController.m#L74). Would you be interested in adding this yourself?
